/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.UberModelDirectory;
import java.awt.CardLayout;

/**
 *
 * @author Anjali
 */
public class MainJFrame extends javax.swing.JFrame {
    private UberModelDirectory uberModelDirectory;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
         
        initComponents();
        this.uberModelDirectory = new UberModelDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        topLayout = new javax.swing.JPanel();
        btnUberService = new javax.swing.JButton();
        userProfileLayout = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topLayout.setBackground(new java.awt.Color(102, 102, 102));
        topLayout.setPreferredSize(new java.awt.Dimension(1300, 100));

        btnUberService.setBackground(new java.awt.Color(0, 0, 0));
        btnUberService.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUberService.setForeground(new java.awt.Color(255, 255, 255));
        btnUberService.setText("Uber Service");
        btnUberService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUberServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topLayoutLayout = new javax.swing.GroupLayout(topLayout);
        topLayout.setLayout(topLayoutLayout);
        topLayoutLayout.setHorizontalGroup(
            topLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayoutLayout.createSequentialGroup()
                .addContainerGap(840, Short.MAX_VALUE)
                .addComponent(btnUberService, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        topLayoutLayout.setVerticalGroup(
            topLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayoutLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(btnUberService, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jSplitPane1.setTopComponent(topLayout);

        userProfileLayout.setBackground(new java.awt.Color(0, 0, 0));
        userProfileLayout.setPreferredSize(new java.awt.Dimension(1300, 782));
        userProfileLayout.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProfileLayout);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUberServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUberServiceActionPerformed
        // TODO add your handling code here:
        UberJPanel panel = new UberJPanel(userProfileLayout,uberModelDirectory);
        userProfileLayout.add("UberJPanel",panel);
        CardLayout layout =(CardLayout) userProfileLayout.getLayout();
        layout.next(userProfileLayout );
    }//GEN-LAST:event_btnUberServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUberService;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel topLayout;
    private javax.swing.JPanel userProfileLayout;
    // End of variables declaration//GEN-END:variables
}
