/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.UberModelDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Anjali
 */
public class UberJPanel extends javax.swing.JPanel {
    private JPanel userProfileLayout;
    private UberModelDirectory uberDirectory;
    /**
     * Creates new form UberJPanel
     */
    public UberJPanel(JPanel userProfileLayout,UberModelDirectory uberDirectory){
        initComponents();
        this.userProfileLayout = userProfileLayout;
        this.uberDirectory = uberDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateVehicle = new javax.swing.JButton();
        btnManageVehicle = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));

        btnCreateVehicle.setBackground(new java.awt.Color(0, 0, 0));
        btnCreateVehicle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCreateVehicle.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateVehicle.setText("Create Vehicle Details ");
        btnCreateVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateVehicleActionPerformed(evt);
            }
        });

        btnManageVehicle.setBackground(new java.awt.Color(0, 0, 0));
        btnManageVehicle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageVehicle.setForeground(new java.awt.Color(255, 255, 255));
        btnManageVehicle.setText("Manage Vehicle Details");
        btnManageVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVehicleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(448, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(437, 437, 437))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(btnCreateVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnManageVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(463, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateVehicleActionPerformed
        // TODO add your handling code here:
        CreateJPanel panel = new CreateJPanel(userProfileLayout,uberDirectory);
         userProfileLayout.add("CreateAccountJPanel",panel);
        CardLayout layout =(CardLayout) userProfileLayout.getLayout();
        layout.next(userProfileLayout);
    }//GEN-LAST:event_btnCreateVehicleActionPerformed

    private void btnManageVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVehicleActionPerformed
        // TODO add your handling code here:
        ManageJPanel panel = new ManageJPanel(this.userProfileLayout,uberDirectory);
        this.userProfileLayout.add("ManageAccountJPanel",panel);
        CardLayout layout =(CardLayout) this.userProfileLayout.getLayout();
        layout.next(userProfileLayout);
    }//GEN-LAST:event_btnManageVehicleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateVehicle;
    private javax.swing.JButton btnManageVehicle;
    // End of variables declaration//GEN-END:variables
}
